Hide more netgroup-related stuff behind ifdefs
Otherwise compiler complains about unused variables when built without
netgroup support (e.g. musl):

 ../src/polkitbackend/polkitbackendduktapeauthority.c: In function 'js_polkit_user_is_in_netgroup':
../src/polkitbackend/polkitbackendduktapeauthority.c:1184:15: error: variable 'netgroup' set but not used [-Werror=unused-but-set-variable]
 1184 |   const char *netgroup;
      |               ^~~~~~~~
../src/polkitbackend/polkitbackendduktapeauthority.c:1183:15: error: variable 'user' set but not used [-Werror=unused-but-set-variable]
 1183 |   const char *user;
      |               ^~~~
cc1: all warnings being treated as errors

 ../src/polkitbackend/polkitbackendinteractiveauthority.c: In function 'get_users_in_net_group':
../src/polkitbackend/polkitbackendinteractiveauthority.c:2279:16: error: unused variable 'name' [-Werror=unused-variable]
 2279 |   const gchar *name;
      |                ^~~~
cc1: all warnings being treated as errors

../src/polkit/polkitidentity.c: In function 'polkit_identity_new_for_gvariant':
../src/polkit/polkitidentity.c:349:19: error: unused variable 'name' [-Werror=unused-variable]
  349 |       const char *name;
      |                   ^~~~
../src/polkit/polkitidentity.c:348:17: error: unused variable 'v' [-Werror=unused-variable]
  348 |       GVariant *v;
      |                 ^
cc1: all warnings being treated as errors