test: don't define test netgroup functions when built without netgroup support
Otherwise compiler complains. Spotted when built with musl, which
doesn't support netgroups:

../test/polkit/polkitunixnetgrouptest.c:44:1: error: 'test_set_name' defined but not used [-Werror=unused-function]
   44 | test_set_name (void)
      | ^~~~~~~~~~~~~
../test/polkit/polkitunixnetgrouptest.c:28:1: error: 'test_new' defined but not used [-Werror=unused-function]
   28 | test_new (void)
      | ^~~~~~~~
cc1: all warnings being treated as errors